apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: linuxserver/jellyfin
        resources:
          limits:
            memory: "1500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8096

        volumeMounts:
        - name: jellyfinconfig
          mountPath: /config
        - name: jellyfinmedia
          mountPath: /data
      volumes:
      - name: jellyfinconfig
        persistentVolumeClaim:
          claimName: jellyfin-config-persistent-volume-claim
      - name: jellyfinmedia
        persistentVolumeClaim:
          claimName: jellyfin-media-persistent-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: jellyfinservice
spec:
  selector:
    app: jellyfin
  ports:
  - port: 80
    targetPort: 8096


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-persistent-volume
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: jellyfin-media-storage-class
  hostPath:
    path: /home/sakthi/kubestorage/jellyfin/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-persistent-volume-claim
spec:
  storageClassName: jellyfin-media-storage-class
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config-persistent-volume
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: jellyfin-config-storage-class
  hostPath:
    path: /home/sakthi/kubestorage/jellyfin/config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-persistent-volume-claim
spec:
  storageClassName: jellyfin-config-storage-class
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany


