apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
      - name: jellyfin
        image: linuxserver/jellyfin
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 8096

---
apiVersion: v1
kind: Service
metadata:
  name: jellyfinservice
spec:
  selector:
    app: jellyfin
  ports:
  - port: 80
    targetPort: 8096


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-persistent-volume
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: jellyfin-storage-class
  hostPath:
    path: /home/sakthi/kubestorage/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-persistent-volume-claim
spec:
  storageClassName: jellyfin-storage-class
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany


